### ISSUE TITLE
Lift `AbstractString` type restriction on `summary` arg of `details`

### ISSUE THREAD

**Issue by genericallyterrible** [JuliaPluto/PlutoUI.jl#295]
`summary` was initially restricted to `AbstractString` to ensure good default behavior. Non-inline elements would easily create undesirable results an end-user could not remedy other than to only use string-like objects. Here is an example with a long heading:

![image](https://github.com/JuliaPluto/PlutoUI.jl/assets/11425944/e013b20e-0036-447b-beb0-af2838bd3e8a)

Even [MDN demonstrates this issue](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary#summaries_as_headings):

![image](https://github.com/JuliaPluto/PlutoUI.jl/assets/11425944/77f7153d-2f01-47ff-a812-b5b5592d55e4)

The restriction of only plain string content within `<summary>` elements is not one enforced by specification and so should be removed, provided an updated implementation can deliver a good default behavior for most simple cases.

Inspired: https://github.com/JuliaPluto/PlutoUI.jl/pull/290#issuecomment-1959312566

**Comment by rgouveiamendes** [comment]
If this helps, for Markdown I somehow got a solution with a pretty straightforward CSS trick:
```css
pluto-output summary > .markdown {
		display:inline-flex;
		max-width:98%;
	}
```
(see for example [here](https://rgouveiamendes.org/teaching/iscte-iul/econometrics-i/notebooks/aula-06).)

**Comment by genericallyterrible** [comment]
Ended up adding a simple div wrapper for non-string values with this set of styles:

```css
pluto-output div.summary-title {
	display: inline-block;
	width: calc(100% - 1em);
	margin-left: -1em;
	padding-left: 1em;
}
```
